//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSnack.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SnackDBEntities : DbContext
    {
        public SnackDBEntities()
            : base("name=SnackDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<z_bas_goods> z_bas_goods { get; set; }
        public virtual DbSet<z_bas_orders> z_bas_orders { get; set; }
        public virtual DbSet<z_bas_orders_d> z_bas_orders_d { get; set; }
    }
}
