//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSnack.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class z_bas_orders
    {
        public int rowid { get; set; }

        [DisplayName("訂單編號")]
        public string mno { get; set; }

        [DisplayName("訂單日期")]
        public string mdate { get; set; }

        [DisplayName("會員帳號")]
        public string userid { get; set; }
        public Nullable<decimal> totals { get; set; }

        [DisplayName("收件人姓名")]
        [Required]
        public string mReceiver { get; set; }

        [DisplayName("收件人信箱")]
        [Required]
        [EmailAddress]
        public string mEmail { get; set; }

        [DisplayName("收件人地址")]
        [Required]
        public string mAddress { get; set; }
        public string remark { get; set; }
    }
}
