//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSnack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class z_bas_orders_d
    {
        public int rowid { get; set; }
        public string mno { get; set; }
        public string userid { get; set; }
        public string gno { get; set; }
        public string gname { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> amounts { get; set; }
        public string remark { get; set; }
        public string mIsApproved { get; set; }
    }
}
