//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSnack.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class z_bas_orders_d
    {
        public int rowid { get; set; }

        [DisplayName("訂單編號")]
        public string mno { get; set; }

        [DisplayName("會員帳號")]
        public string userid { get; set; }

        [DisplayName("商品編號")]
        public string gno { get; set; }

        [DisplayName("商品名稱")]
        public string gname { get; set; }

        [DisplayName("單價")]
        public Nullable<decimal> price { get; set; }

        [DisplayName("訂購數量")]
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> amounts { get; set; }
        public string remark { get; set; }

        [DisplayName("是否為訂單")]
        public string mIsApproved { get; set; }
    }
}
